/**
 * ,--.,------. ,----.   ,------.,--.  ,--. 
 * |  ||  .---''  .-.|   |  .---'|  ,'.|  | 
 * |  ||  `--, |  | .---.|  `--, |  |' '  | 
 * |  ||  `---.'  '--'  ||  `---.|  | `   | 
 * `--'`------' `------' `------'`--'  `--' 
 * 
 * This file is generated by iegen on 12/08/2021-11:58.
 * Please do not change it manually.
 */

import CWrapper
import Foundation

public class Integer {

  public let cself: CObject
  public let owner: Bool

  // internal main initializer
  internal required init(_ _cself: CObject, _ _owner: Bool = false) {
    self.cself = _cself
    self.owner = _owner
  }

  deinit {
    release_Integer(cself, owner)
  }

  public convenience init(n: Int) {
    let swifttoscn = CInt(n)
    var err = ErrorObj()
    self.init(create_Integer(swifttoscn, &err), true)
    let errorType = Int(err.err_type)
    if errorType != 0 {
      switch errorType {
      case (1):
        let excObj = StdException(CObject(type: strdup("std::exception"), ptr: err.err_ptr), true)
        ExceptionHandler.handleUncaughtException(excObj.what())
      default:
        ExceptionHandler.handleUncaughtException("Uncaught Exception")
      }
    }
  }

  /**
   * value getter
   */
  public var value: Int {
    get {
      let result = _prop_get_Integer_value(cself)
      let sctoswiftresult = Int(result)
      return sctoswiftresult
    }
  }

}

public class MiscExc {

  public let cself: CObject
  public let owner: Bool

  // internal main initializer
  internal required init(_ _cself: CObject, _ _owner: Bool = false) {
    self.cself = _cself
    self.owner = _owner
  }

  deinit {
    release_MiscExc(cself, owner)
  }

  public static func returnInteger(doThrow: Bool) throws -> Integer {

    var err = ErrorObj()
    let result = _func_MiscExc_returnInteger(doThrow, &err)
    let errorType = Int(err.err_type)
    if errorType != 0 {
      switch errorType {
      case (1):
        throw StdOutOfRange(CObject(type: strdup("std::out_of_range"), ptr: err.err_ptr), true)
      case (2):
        let excObj = StdException(CObject(type: strdup("std::exception"), ptr: err.err_ptr), true)
        ExceptionHandler.handleUncaughtException(excObj.what())
      default:
        ExceptionHandler.handleUncaughtException("Uncaught Exception")
      }
    }
    var sctoswiftresult: Integer
    sctoswiftresult = Integer(result)
    return sctoswiftresult
  }

  public static func raiseErrorByType(errType: String) throws -> Void {

    let swifttoscerrType = strdup(errType)!
    var err = ErrorObj()
    _func_MiscExc_raiseErrorByType(swifttoscerrType, &err)
    let errorType = Int(err.err_type)
    if errorType != 0 {
      switch errorType {
      case (1):
        throw StdRuntimeError(CObject(type: strdup("std::runtime_error"), ptr: err.err_ptr), true)
      case (2):
        throw FileError(CObject(type: strdup("iegen::example::FileError"), ptr: err.err_ptr), true)
      case (3):
        throw SystemError(CObject(type: strdup("iegen::example::SystemError"), ptr: err.err_ptr), true)
      case (4):
        throw SimpleChildException(CObject(type: strdup("iegen::example::SimpleChildException"), ptr: err.err_ptr), true)
      case (5):
        throw SimpleBaseException(CObject(type: strdup("iegen::example::SimpleBaseException"), ptr: err.err_ptr), true)
      case (6):
        throw StdException(CObject(type: strdup("std::exception"), ptr: err.err_ptr), true)
      default:
        ExceptionHandler.handleUncaughtException("Uncaught Exception")
      }
    }
  }

}
